### ISSUE TITLE
Is this project discontinued?

### ISSUE THREAD

**Issue by miguelgmalpha** [awslabs/amazon-apigateway-ingress-controller#23]
Hi there

Is this project actively maintained? I've seen that the last commit to the master branch is about one year old?

Is this supported in another repo or what is the plan for this?

Thank you

**Comment by ltearno** [comment]
Yes, I am also very unclear about should I use this project (because maintaining it is not an option for me).
I'd like to know wether this project is deprecated or not please !

**Comment by miguelgmalpha** [comment]
I suppose this is discontinued in favor of https://aws.amazon.com/blogs/containers/aws-controllers-for-kubernetes-ack/

https://aws.github.io/aws-controllers-k8s/

**Comment by ltearno** [comment]
thanks @miguelgmalpha but there is this on the  website :

**Until we've graduated ACK service controllers we ask you to test-drive them.**

Anyway thanks, that's maybe a project to watch !

**Comment by mercuriete** [comment]
I had this URL in a tab
https://aws.amazon.com/es/blogs/containers/api-gateway-as-an-ingress-controller-for-eks

it is still in google cache:
https://webcache.googleusercontent.com/search?q=cache:PiKcytsVyGoJ:https://aws.amazon.com/blogs/containers/api-gateway-as-an-ingress-controller-for-eks

And now it gives me 404.
So definitely this is discontinued.

Thanks for this project but I am not able to deploy without a real walkthrough or documentation.
