### ISSUE TITLE
Multiple NodeInstanceRole

### ISSUE THREAD

**Issue by hieu29791** [awslabs/amazon-apigateway-ingress-controller#8]
Hi,
I have 2 NodeInstanceRole, how do I configure this on **kube2iam-ingress-trust-policy.yml** file. I try this and can not create Role.

> "Principal": {
        "AWS": "arn:aws:iam::xxx:role/worker-nodes-2-NodeInstanceRole-xxxxxxx"
        "AWS": "arn:aws:iam::xxx:role/worker-nodes-NodeInstanceRole-xxxxxxx"
      },

Thanks

**Comment by Magizhchi** [comment]
Can you try entering it as a Comma Separated Value like this :
```
"Principal": {
"AWS": "arn:aws:iam::xxx:role/worker-nodes-2-NodeInstanceRole-xxxxxxx, arn:aws:iam::xxx:role/worker-nodes-NodeInstanceRole-xxxxxxx"
}
```

**Comment by hieu29791** [comment]
> Can you try entering it as a Comma Separated Value like this :
> 
> ```
> "Principal": {
> "AWS": "arn:aws:iam::xxx:role/worker-nodes-2-NodeInstanceRole-xxxxxxx, arn:aws:iam::xxx:role/worker-nodes-NodeInstanceRole-xxxxxxx"
> }
> ```

I tried it but error appears:

> An error occurred (MalformedPolicyDocument) when calling the CreateRole operation: Invalid principal in policy: "AWS":"arn:aws:iam::xxxx:role/xxxxxxxxx, arn:aws:iam::xxxxx:role/xxxxxxxx"

So I read on this link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html
The correct syntax must be:
```
"Principal": {
                        "AWS": [
                            "arn:aws:iam::xxxxx:role/worker-node-1",
                            "arn:aws:iam::xxxxx:role/worker-node-2"
                        ]
                    },
```
